apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejs-container
        image: dheeraj394/nodejs:01
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.37.247
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
