apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejsapp
  namespace: argocd  # Argo CD's namespace
spec:
  project: default

  source:
    repoURL: https://github.com/kumardheeraj394/k8s_demo.git
    targetRevision: HEAD
    path: k8s-manifests  # Adjust this to the correct directory in your repo

  destination:
    server: https://kubernetes.default.svc  # Deploy into the same cluster
    namespace: nodejsapp  # Target namespace (should exist or be created)

  syncPolicy:
    automated:
      prune: true         # Automatically delete resources no longer in Git
      selfHeal: true      # Automatically fix out-of-sync resources
    syncOptions:
    - CreateNamespace=true  # Creates the namespace if it doesn’t exist
