apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  labels:
    app: nodejsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: dheeraj394/nodejs:03
        ports:
        - containerPort: 3000
