apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  loadBalancerIP: 10.10.37.247
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp2
spec:
  selector:
    app: nodejsapp2
  type: LoadBalancer
  loadBalancerIP: 10.10.37.247
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

